/**
 * Interface copy for site 3.
 *
 * The voice here is a tool's, not a brochure's: labels, units, shortcuts and
 * empty states. Every figure still comes from content.json.
 */

const en = {
  meta: {
    title: 'Investor Explorer — Invest in Uzbekistan',
    description:
      'Regions, priority sectors, a journey configurator and live FX, in one interactive view. Concept/demo project — official information: invest.gov.uz',
  },
  appName: 'Investor Explorer',
  skip: 'Skip to content',
  nav: {
    label: 'Sections',
    overview: 'Overview',
    map: 'Map',
    sectors: 'Sectors',
    configurator: 'Configurator',
    calculator: 'FX calculator',
    indicators: 'Indicators',
    contact: 'Contact',
  },
  actions: {
    search: 'Search',
    close: 'Close',
    clear: 'Clear',
    copy: 'Copy',
    copied: 'Copied',
    retry: 'Try again',
    downloadCsv: 'Download CSV',
    openOfficial: 'Official page',
    grid: 'Grid',
    list: 'List',
    shortcuts: 'Keyboard shortcuts',
    reset: 'Reset',
    send: 'Send enquiry',
    sending: 'Sending…',
  },
  state: {
    loading: 'Loading…',
    errorTitle: 'Could not load the data',
    errorBody: 'Every figure here comes from one data file, and it did not load.',
    empty: 'Nothing matches.',
    noData: '—',
    noMap: 'The region outlines could not be loaded. The table below has the same figures.',
  },
  palette: {
    label: 'Command palette',
    placeholder: 'Jump to a section, sector or region…',
    hint: 'Ctrl K',
    groups: { sections: 'Sections', sectors: 'Sectors', regions: 'Regions' },
  },
  shortcuts: {
    title: 'Keyboard shortcuts',
    palette: 'Command palette',
    search: 'Focus search',
    panels: 'Switch section',
    help: 'This list',
    escape: 'Close',
  },
  overview: {
    title: 'Uzbekistan at a glance',
    about: 'About the Agency',
    cta: 'Send an investment enquiry',
    ctaBody: 'The Agency is the primary point of contact with the state for foreign investors.',
    fxTile: 'Central Bank rate',
  },
  map: {
    title: 'Regions',
    body: 'Fourteen regions, shaded by average monthly salary. Select one for its profile.',
    legend: 'Average monthly salary',
    unit: 'thousand UZS / month',
    nationalAverage: 'National average',
    pickHint: 'Select a region on the map.',
    profileMissing:
      'Only Karakalpakstan has a full regional profile in the source data. Fields without an official figure are left as “—” rather than estimated.',
    profile: {
      population: 'Population',
      births: 'Births, 2025',
      employed: 'Employed',
      workingAge: 'Working-age population',
      employmentRate: 'Employment rate',
      unemploymentRate: 'Unemployment rate',
      universities: 'Universities',
      students: 'Students',
      specializations: 'Specialisations',
      salary: 'Average monthly salary',
    },
    units: { thousand: 'k', percent: '%' },
  },
  sectors: {
    title: 'Priority sectors',
    body: 'Ten sectors, with a link to the Agency page for each.',
    searchLabel: 'Search sectors',
    count: (n: number, total: number) => `${n} / ${total}`,
  },
  configurator: {
    title: 'Investor journey configurator',
    body: 'Three questions, then the services and next steps that apply.',
    q1: 'Sector',
    q2: 'Investment size',
    q3: 'Region',
    any: 'Any',
    resultTitle: 'What the Agency can do',
    stepsTitle: 'Next steps',
    sezTitle: 'Special economic zones',
    disclaimer: 'This is not tax or legal advice. Check current legislation at lex.uz.',
  },
  calculator: {
    title: 'Currency calculator',
    body: 'Central Bank of Uzbekistan rates. Falls back to the stored rate when the live request fails.',
    amount: 'Amount',
    from: 'Currency',
    result: 'In Uzbek soʻm',
    live: 'Live rate',
    stored: 'Stored rate',
    asOf: (date: string) => `as of ${date}`,
    unavailable: 'No rate available',
    rateLine: (ccy: string, rate: string) => `1 ${ccy} = ${rate} UZS`,
  },
  indicators: {
    title: 'All indicators',
    body: 'Every figure on this site, sortable, with its source and date.',
    columns: { indicator: 'Indicator', value: 'Value', group: 'Group', source: 'Source', asOf: 'As of' },
    groups: { economy: 'Economy 2025', human: 'Human capital', tiif: 'TIIF 2026', regions: 'Regions' },
  },
  forum: { title: 'TIIF 2026', held: 'Held', past: 'This forum has taken place.', site: 'Forum website' },
  contact: {
    title: 'Contact',
    body: 'Write, call, or send an enquiry.',
    phone: 'Phone',
    email: 'Email',
    address: 'Address',
    map: 'Open in Maps',
    website: 'Website',
    form: { name: 'Name', email: 'Work email', message: 'Message' },
    errors: {
      name: 'Please enter your name.',
      email: 'Please enter a valid email address.',
      message: 'Please write a short message.',
    },
    sent: 'Your enquiry is ready to send.',
    sentPosted: 'Your enquiry has been submitted.',
    failed: 'The enquiry could not be sent. Please write to the address above.',
  },
  sources: {
    label: 'Source',
    asOf: (date: string) => `as of ${date}`,
    title: 'Sources',
    machine: 'The Russian text here was translated from English and is not an official text.',
  },
  footer: {
    links: 'Official links',
    disclaimerTitle: 'Concept project',
    disclaimer:
      'This site is a concept/demo project and is not operated by the Agency. For official information see invest.gov.uz.',
    geoCredit: 'Region outlines: geoBoundaries (ODbL 1.0)',
  },
};

export type UiStrings = typeof en;

const uz: UiStrings = {
  meta: {
    title: 'Investor Explorer — Invest in Uzbekistan',
    description:
      'Hududlar, ustuvor sektorlar, investor yoʻli konfiguratori va jonli valyuta kursi — bitta interaktiv oynada. Konsept/demo loyiha — rasmiy maʼlumot: invest.gov.uz',
  },
  appName: 'Investor Explorer',
  skip: 'Asosiy mazmunga oʻtish',
  nav: {
    label: 'Boʻlimlar',
    overview: 'Umumiy',
    map: 'Xarita',
    sectors: 'Sektorlar',
    configurator: 'Konfigurator',
    calculator: 'Valyuta kalkulyatori',
    indicators: 'Koʻrsatkichlar',
    contact: 'Aloqa',
  },
  actions: {
    search: 'Qidirish',
    close: 'Yopish',
    clear: 'Tozalash',
    copy: 'Nusxa olish',
    copied: 'Nusxa olindi',
    retry: 'Qayta urinish',
    downloadCsv: 'CSV yuklab olish',
    openOfficial: 'Rasmiy sahifa',
    grid: 'Katak',
    list: 'Roʻyxat',
    shortcuts: 'Klaviatura yorliqlari',
    reset: 'Tiklash',
    send: 'Soʻrov yuborish',
    sending: 'Yuborilmoqda…',
  },
  state: {
    loading: 'Yuklanmoqda…',
    errorTitle: 'Maʼlumotni yuklab boʻlmadi',
    errorBody: 'Bu yerdagi har bir raqam bitta maʼlumot faylidan olinadi — u yuklanmadi.',
    empty: 'Mos natija yoʻq.',
    noData: '—',
    noMap: 'Hudud chegaralarini yuklab boʻlmadi. Quyidagi jadvalda oʻsha raqamlar bor.',
  },
  palette: {
    label: 'Buyruqlar paneli',
    placeholder: 'Boʻlim, sektor yoki hududga oʻtish…',
    hint: 'Ctrl K',
    groups: { sections: 'Boʻlimlar', sectors: 'Sektorlar', regions: 'Hududlar' },
  },
  shortcuts: {
    title: 'Klaviatura yorliqlari',
    palette: 'Buyruqlar paneli',
    search: 'Qidiruvga oʻtish',
    panels: 'Boʻlimni almashtirish',
    help: 'Shu roʻyxat',
    escape: 'Yopish',
  },
  overview: {
    title: 'Oʻzbekiston qisqacha',
    about: 'Agentlik haqida',
    cta: 'Investitsiya soʻrovi yuborish',
    ctaBody: 'Agentlik — xorijiy investorlar uchun davlat bilan asosiy aloqa nuqtasi.',
    fxTile: 'Markaziy bank kursi',
  },
  map: {
    title: 'Hududlar',
    body: 'Oʻn toʻrt hudud, oʻrtacha oylik maosh boʻyicha ranglangan. Profilini koʻrish uchun tanlang.',
    legend: 'Oʻrtacha oylik maosh',
    unit: 'ming soʻm / oyiga',
    nationalAverage: 'Respublika oʻrtachasi',
    pickHint: 'Xaritadan hududni tanlang.',
    profileMissing:
      'Manba maʼlumotlarida faqat Qoraqalpogʻiston uchun toʻliq profil bor. Rasmiy raqami yoʻq maydonlar taxmin qilinmay, “—” qoldirilgan.',
    profile: {
      population: 'Aholi',
      births: '2025 yilda tugʻilganlar',
      employed: 'Band aholi',
      workingAge: 'Mehnatga layoqatli aholi',
      employmentRate: 'Bandlik darajasi',
      unemploymentRate: 'Ishsizlik darajasi',
      universities: 'Oliy taʼlim muassasalari',
      students: 'Talabalar',
      specializations: 'Ixtisosliklar',
      salary: 'Oʻrtacha oylik maosh',
    },
    units: { thousand: 'ming', percent: '%' },
  },
  sectors: {
    title: 'Ustuvor sektorlar',
    body: 'Oʻnta sektor, har biri uchun agentlik sahifasiga havola.',
    searchLabel: 'Sektorlarni qidirish',
    count: (n: number, total: number) => `${n} / ${total}`,
  },
  configurator: {
    title: 'Investor yoʻli konfiguratori',
    body: 'Uchta savol — soʻng mos xizmatlar va keyingi qadamlar.',
    q1: 'Sektor',
    q2: 'Investitsiya hajmi',
    q3: 'Hudud',
    any: 'Farqi yoʻq',
    resultTitle: 'Agentlik nima qila oladi',
    stepsTitle: 'Keyingi qadamlar',
    sezTitle: 'Maxsus iqtisodiy zonalar',
    disclaimer: 'Bu soliq yoki huquqiy maslahat emas. Amaldagi qonunchilikni lex.uz da tekshiring.',
  },
  calculator: {
    title: 'Valyuta kalkulyatori',
    body: 'Oʻzbekiston Markaziy banki kurslari. Jonli soʻrov muvaffaqiyatsiz boʻlsa, saqlangan kursga qaytadi.',
    amount: 'Miqdor',
    from: 'Valyuta',
    result: 'Oʻzbek soʻmida',
    live: 'Jonli kurs',
    stored: 'Saqlangan kurs',
    asOf: (date: string) => `${date} holatiga`,
    unavailable: 'Kurs mavjud emas',
    rateLine: (ccy: string, rate: string) => `1 ${ccy} = ${rate} soʻm`,
  },
  indicators: {
    title: 'Barcha koʻrsatkichlar',
    body: 'Saytdagi har bir raqam — tartiblanadigan, manbasi va sanasi bilan.',
    columns: { indicator: 'Koʻrsatkich', value: 'Qiymat', group: 'Guruh', source: 'Manba', asOf: 'Sana' },
    groups: { economy: 'Iqtisodiyot 2025', human: 'Inson kapitali', tiif: 'TIIF 2026', regions: 'Hududlar' },
  },
  forum: { title: 'TIIF 2026', held: 'Oʻtkazilgan', past: 'Bu forum boʻlib oʻtgan.', site: 'Forum sayti' },
  contact: {
    title: 'Aloqa',
    body: 'Yozing, qoʻngʻiroq qiling yoki soʻrov yuboring.',
    phone: 'Telefon',
    email: 'Elektron pochta',
    address: 'Manzil',
    map: 'Xaritada ochish',
    website: 'Sayt',
    form: { name: 'Ism', email: 'Ish elektron pochtasi', message: 'Xabar' },
    errors: {
      name: 'Ismingizni kiriting.',
      email: 'Toʻgʻri elektron pochta manzilini kiriting.',
      message: 'Qisqa xabar yozing.',
    },
    sent: 'Soʻrovingiz yuborishga tayyor.',
    sentPosted: 'Soʻrovingiz yuborildi.',
    failed: 'Soʻrovni yuborib boʻlmadi. Iltimos, yuqoridagi manzilga yozing.',
  },
  sources: {
    label: 'Manba',
    asOf: (date: string) => `${date} holatiga`,
    title: 'Manbalar',
    machine: 'Bu yerdagi ruscha matn ingliz tilidan tarjima qilingan va rasmiy matn emas.',
  },
  footer: {
    links: 'Rasmiy havolalar',
    disclaimerTitle: 'Konsept loyiha',
    disclaimer:
      'Ushbu sayt konsept/demo loyiha boʻlib, agentlik tomonidan yuritilmaydi. Rasmiy maʼlumot uchun: invest.gov.uz.',
    geoCredit: 'Hudud chegaralari: geoBoundaries (ODbL 1.0)',
  },
};

const ru: UiStrings = {
  meta: {
    title: 'Investor Explorer — Invest in Uzbekistan',
    description:
      'Регионы, приоритетные отрасли, конфигуратор пути инвестора и актуальный курс — в одном интерактивном окне. Концепт/демо — официальная информация: invest.gov.uz',
  },
  appName: 'Investor Explorer',
  skip: 'Перейти к содержимому',
  nav: {
    label: 'Разделы',
    overview: 'Обзор',
    map: 'Карта',
    sectors: 'Отрасли',
    configurator: 'Конфигуратор',
    calculator: 'Калькулятор валют',
    indicators: 'Показатели',
    contact: 'Контакты',
  },
  actions: {
    search: 'Поиск',
    close: 'Закрыть',
    clear: 'Очистить',
    copy: 'Копировать',
    copied: 'Скопировано',
    retry: 'Попробовать снова',
    downloadCsv: 'Скачать CSV',
    openOfficial: 'Официальная страница',
    grid: 'Плитка',
    list: 'Список',
    shortcuts: 'Горячие клавиши',
    reset: 'Сбросить',
    send: 'Отправить запрос',
    sending: 'Отправка…',
  },
  state: {
    loading: 'Загрузка…',
    errorTitle: 'Не удалось загрузить данные',
    errorBody: 'Все цифры здесь берутся из одного файла данных — он не загрузился.',
    empty: 'Ничего не найдено.',
    noData: '—',
    noMap: 'Не удалось загрузить контуры регионов. В таблице ниже те же цифры.',
  },
  palette: {
    label: 'Командная палитра',
    placeholder: 'Перейти к разделу, отрасли или региону…',
    hint: 'Ctrl K',
    groups: { sections: 'Разделы', sectors: 'Отрасли', regions: 'Регионы' },
  },
  shortcuts: {
    title: 'Горячие клавиши',
    palette: 'Командная палитра',
    search: 'Фокус на поиск',
    panels: 'Переключить раздел',
    help: 'Этот список',
    escape: 'Закрыть',
  },
  overview: {
    title: 'Узбекистан вкратце',
    about: 'Об Агентстве',
    cta: 'Отправить инвестиционный запрос',
    ctaBody: 'Агентство — основная точка контакта с государством для иностранных инвесторов.',
    fxTile: 'Курс Центрального банка',
  },
  map: {
    title: 'Регионы',
    body: 'Четырнадцать регионов, окрашенных по средней зарплате. Выберите один, чтобы увидеть профиль.',
    legend: 'Средняя месячная зарплата',
    unit: 'тыс. сум / месяц',
    nationalAverage: 'Среднее по стране',
    pickHint: 'Выберите регион на карте.',
    profileMissing:
      'В исходных данных полный профиль есть только у Каракалпакстана. Поля без официальной цифры оставлены как «—», а не оценены.',
    profile: {
      population: 'Население',
      births: 'Рождений в 2025',
      employed: 'Занятые',
      workingAge: 'Население в трудоспособном возрасте',
      employmentRate: 'Уровень занятости',
      unemploymentRate: 'Уровень безработицы',
      universities: 'Вузы',
      students: 'Студенты',
      specializations: 'Специализации',
      salary: 'Средняя месячная зарплата',
    },
    units: { thousand: 'тыс.', percent: '%' },
  },
  sectors: {
    title: 'Приоритетные отрасли',
    body: 'Десять отраслей со ссылкой на страницу Агентства по каждой.',
    searchLabel: 'Поиск по отраслям',
    count: (n: number, total: number) => `${n} / ${total}`,
  },
  configurator: {
    title: 'Конфигуратор пути инвестора',
    body: 'Три вопроса — затем подходящие услуги и следующие шаги.',
    q1: 'Отрасль',
    q2: 'Объём инвестиций',
    q3: 'Регион',
    any: 'Любой',
    resultTitle: 'Что может сделать Агентство',
    stepsTitle: 'Следующие шаги',
    sezTitle: 'Специальные экономические зоны',
    disclaimer: 'Это не налоговая и не юридическая консультация. Проверяйте законодательство на lex.uz.',
  },
  calculator: {
    title: 'Калькулятор валют',
    body: 'Курсы Центрального банка Узбекистана. При сбое запроса используется сохранённый курс.',
    amount: 'Сумма',
    from: 'Валюта',
    result: 'В узбекских сумах',
    live: 'Актуальный курс',
    stored: 'Сохранённый курс',
    asOf: (date: string) => `на ${date}`,
    unavailable: 'Курс недоступен',
    rateLine: (ccy: string, rate: string) => `1 ${ccy} = ${rate} сум`,
  },
  indicators: {
    title: 'Все показатели',
    body: 'Каждая цифра сайта — с сортировкой, источником и датой.',
    columns: { indicator: 'Показатель', value: 'Значение', group: 'Группа', source: 'Источник', asOf: 'На дату' },
    groups: { economy: 'Экономика 2025', human: 'Человеческий капитал', tiif: 'ТМИФ 2026', regions: 'Регионы' },
  },
  forum: { title: 'ТМИФ 2026', held: 'Проведён', past: 'Форум уже состоялся.', site: 'Сайт форума' },
  contact: {
    title: 'Контакты',
    body: 'Напишите, позвоните или отправьте запрос.',
    phone: 'Телефон',
    email: 'Эл. почта',
    address: 'Адрес',
    map: 'Открыть на карте',
    website: 'Сайт',
    form: { name: 'Имя', email: 'Рабочая почта', message: 'Сообщение' },
    errors: {
      name: 'Укажите ваше имя.',
      email: 'Укажите корректный адрес электронной почты.',
      message: 'Напишите короткое сообщение.',
    },
    sent: 'Ваш запрос готов к отправке.',
    sentPosted: 'Ваш запрос отправлен.',
    failed: 'Не удалось отправить запрос. Напишите на адрес выше.',
  },
  sources: {
    label: 'Источник',
    asOf: (date: string) => `на ${date}`,
    title: 'Источники',
    machine: 'Русский текст здесь переведён с английского и не является официальным.',
  },
  footer: {
    links: 'Официальные ссылки',
    disclaimerTitle: 'Концептуальный проект',
    disclaimer:
      'Этот сайт — концепт/демо и не ведётся Агентством. За официальной информацией обращайтесь на invest.gov.uz.',
    geoCredit: 'Контуры регионов: geoBoundaries (ODbL 1.0)',
  },
};

export const UI = { uz, ru, en } as const;
