import js from '@eslint/js';
import globals from 'globals';
import svelte from 'eslint-plugin-svelte';
import tseslint from 'typescript-eslint';
import svelteConfig from './svelte.config.js';

export default tseslint.config(
  {
    // Generated by scripts/sync-shared.mjs; dist/ and dev-dist/ are build output.
    ignores: ['dist', 'dev-dist', 'src/lib/shared', 'src/styles/tokens.css'],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  ...svelte.configs.recommended,
  {
    languageOptions: { ecmaVersion: 2022, globals: globals.browser },
  },
  {
    // svelte-eslint-parser handles the component shell; the TypeScript parser
    // has to be handed to it explicitly for `<script lang="ts">` blocks.
    files: ['**/*.svelte', '**/*.svelte.ts'],
    languageOptions: {
      parserOptions: {
        parser: tseslint.parser,
        extraFileExtensions: ['.svelte'],
        svelteConfig,
      },
    },
  },
  {
    rules: {
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
    },
  },
);
